[tools]
go = "1.26.0"
jq = "latest"
just = "latest"
biome = "latest"
"go:github.com/charmbracelet/vhs" = "v0.11.0"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "v2.12.2"
"go:github.com/pressly/goose/v3/cmd/goose" = "v3.27.2"
"go:github.com/vektra/mockery/v3" = "v3.7.1"
"go:gotest.tools/gotestsum" = "v1.13.0"
