// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbmock

import (
	"context"

	"github.com/robherley/snips.sh/internal/snips"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIKeys creates a new instance of MockAPIKeys. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeys(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeys {
	mock := &MockAPIKeys{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeys is an autogenerated mock type for the APIKeys type
type MockAPIKeys struct {
	mock.Mock
}

type MockAPIKeys_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeys) EXPECT() *MockAPIKeys_Expecter {
	return &MockAPIKeys_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAPIKeys
func (_mock *MockAPIKeys) Create(ctx context.Context, key *snips.APIKey, maxKeys uint64) error {
	ret := _mock.Called(ctx, key, maxKeys)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.APIKey, uint64) error); ok {
		r0 = returnFunc(ctx, key, maxKeys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeys_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAPIKeys_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - key *snips.APIKey
//   - maxKeys uint64
func (_e *MockAPIKeys_Expecter) Create(ctx any, key any, maxKeys any) *MockAPIKeys_Create_Call {
	return &MockAPIKeys_Create_Call{Call: _e.mock.On("Create", ctx, key, maxKeys)}
}

func (_c *MockAPIKeys_Create_Call) Run(run func(ctx context.Context, key *snips.APIKey, maxKeys uint64)) *MockAPIKeys_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snips.APIKey
		if args[1] != nil {
			arg1 = args[1].(*snips.APIKey)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIKeys_Create_Call) Return(err error) *MockAPIKeys_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeys_Create_Call) RunAndReturn(run func(ctx context.Context, key *snips.APIKey, maxKeys uint64) error) *MockAPIKeys_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAPIKeys
func (_mock *MockAPIKeys) Delete(ctx context.Context, id string, userID string) (bool, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeys_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAPIKeys_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockAPIKeys_Expecter) Delete(ctx any, id any, userID any) *MockAPIKeys_Delete_Call {
	return &MockAPIKeys_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *MockAPIKeys_Delete_Call) Run(run func(ctx context.Context, id string, userID string)) *MockAPIKeys_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIKeys_Delete_Call) Return(b bool, err error) *MockAPIKeys_Delete_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAPIKeys_Delete_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) (bool, error)) *MockAPIKeys_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTokenHash provides a mock function for the type MockAPIKeys
func (_mock *MockAPIKeys) FindByTokenHash(ctx context.Context, tokenHash string) (*snips.APIKey, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByTokenHash")
	}

	var r0 *snips.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*snips.APIKey, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *snips.APIKey); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeys_FindByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTokenHash'
type MockAPIKeys_FindByTokenHash_Call struct {
	*mock.Call
}

// FindByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockAPIKeys_Expecter) FindByTokenHash(ctx any, tokenHash any) *MockAPIKeys_FindByTokenHash_Call {
	return &MockAPIKeys_FindByTokenHash_Call{Call: _e.mock.On("FindByTokenHash", ctx, tokenHash)}
}

func (_c *MockAPIKeys_FindByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockAPIKeys_FindByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeys_FindByTokenHash_Call) Return(aPIKey *snips.APIKey, err error) *MockAPIKeys_FindByTokenHash_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeys_FindByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*snips.APIKey, error)) *MockAPIKeys_FindByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUser provides a mock function for the type MockAPIKeys
func (_mock *MockAPIKeys) FindByUser(ctx context.Context, userID string) ([]*snips.APIKey, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUser")
	}

	var r0 []*snips.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*snips.APIKey, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*snips.APIKey); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*snips.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeys_FindByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUser'
type MockAPIKeys_FindByUser_Call struct {
	*mock.Call
}

// FindByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAPIKeys_Expecter) FindByUser(ctx any, userID any) *MockAPIKeys_FindByUser_Call {
	return &MockAPIKeys_FindByUser_Call{Call: _e.mock.On("FindByUser", ctx, userID)}
}

func (_c *MockAPIKeys_FindByUser_Call) Run(run func(ctx context.Context, userID string)) *MockAPIKeys_FindByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeys_FindByUser_Call) Return(aPIKeys []*snips.APIKey, err error) *MockAPIKeys_FindByUser_Call {
	_c.Call.Return(aPIKeys, err)
	return _c
}

func (_c *MockAPIKeys_FindByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*snips.APIKey, error)) *MockAPIKeys_FindByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function for the type MockAPIKeys
func (_mock *MockAPIKeys) Touch(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeys_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type MockAPIKeys_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAPIKeys_Expecter) Touch(ctx any, id any) *MockAPIKeys_Touch_Call {
	return &MockAPIKeys_Touch_Call{Call: _e.mock.On("Touch", ctx, id)}
}

func (_c *MockAPIKeys_Touch_Call) Run(run func(ctx context.Context, id string)) *MockAPIKeys_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeys_Touch_Call) Return(err error) *MockAPIKeys_Touch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeys_Touch_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockAPIKeys_Touch_Call {
	_c.Call.Return(run)
	return _c
}
