// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbmock

import (
	"context"

	"github.com/robherley/snips.sh/internal/db"
	"github.com/robherley/snips.sh/internal/snips"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFiles creates a new instance of MockFiles. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFiles(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFiles {
	mock := &MockFiles{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFiles is an autogenerated mock type for the Files type
type MockFiles struct {
	mock.Mock
}

type MockFiles_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFiles) EXPECT() *MockFiles_Expecter {
	return &MockFiles_Expecter{mock: &_m.Mock}
}

// CountByUser provides a mock function for the type MockFiles
func (_mock *MockFiles) CountByUser(ctx context.Context, userID string) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFiles_CountByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUser'
type MockFiles_CountByUser_Call struct {
	*mock.Call
}

// CountByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFiles_Expecter) CountByUser(ctx any, userID any) *MockFiles_CountByUser_Call {
	return &MockFiles_CountByUser_Call{Call: _e.mock.On("CountByUser", ctx, userID)}
}

func (_c *MockFiles_CountByUser_Call) Run(run func(ctx context.Context, userID string)) *MockFiles_CountByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFiles_CountByUser_Call) Return(n int64, err error) *MockFiles_CountByUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFiles_CountByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) (int64, error)) *MockFiles_CountByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockFiles
func (_mock *MockFiles) Create(ctx context.Context, file *snips.File, content []byte, maxFiles uint64) error {
	ret := _mock.Called(ctx, file, content, maxFiles)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.File, []byte, uint64) error); ok {
		r0 = returnFunc(ctx, file, content, maxFiles)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFiles_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFiles_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - file *snips.File
//   - content []byte
//   - maxFiles uint64
func (_e *MockFiles_Expecter) Create(ctx any, file any, content any, maxFiles any) *MockFiles_Create_Call {
	return &MockFiles_Create_Call{Call: _e.mock.On("Create", ctx, file, content, maxFiles)}
}

func (_c *MockFiles_Create_Call) Run(run func(ctx context.Context, file *snips.File, content []byte, maxFiles uint64)) *MockFiles_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snips.File
		if args[1] != nil {
			arg1 = args[1].(*snips.File)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFiles_Create_Call) Return(err error) *MockFiles_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFiles_Create_Call) RunAndReturn(run func(ctx context.Context, file *snips.File, content []byte, maxFiles uint64) error) *MockFiles_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockFiles
func (_mock *MockFiles) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFiles_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFiles_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFiles_Expecter) Delete(ctx any, id any) *MockFiles_Delete_Call {
	return &MockFiles_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockFiles_Delete_Call) Run(run func(ctx context.Context, id string)) *MockFiles_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFiles_Delete_Call) Return(err error) *MockFiles_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFiles_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockFiles_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUser provides a mock function for the type MockFiles
func (_mock *MockFiles) DeleteByUser(ctx context.Context, userID string) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFiles_DeleteByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUser'
type MockFiles_DeleteByUser_Call struct {
	*mock.Call
}

// DeleteByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFiles_Expecter) DeleteByUser(ctx any, userID any) *MockFiles_DeleteByUser_Call {
	return &MockFiles_DeleteByUser_Call{Call: _e.mock.On("DeleteByUser", ctx, userID)}
}

func (_c *MockFiles_DeleteByUser_Call) Run(run func(ctx context.Context, userID string)) *MockFiles_DeleteByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFiles_DeleteByUser_Call) Return(n int64, err error) *MockFiles_DeleteByUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFiles_DeleteByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) (int64, error)) *MockFiles_DeleteByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockFiles
func (_mock *MockFiles) Find(ctx context.Context, id string) (*snips.File, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *snips.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*snips.File, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *snips.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFiles_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockFiles_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFiles_Expecter) Find(ctx any, id any) *MockFiles_Find_Call {
	return &MockFiles_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockFiles_Find_Call) Run(run func(ctx context.Context, id string)) *MockFiles_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFiles_Find_Call) Return(file *snips.File, err error) *MockFiles_Find_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFiles_Find_Call) RunAndReturn(run func(ctx context.Context, id string) (*snips.File, error)) *MockFiles_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockFiles
func (_mock *MockFiles) FindByName(ctx context.Context, userID string, name string) (*snips.File, error) {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *snips.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*snips.File, error)); ok {
		return returnFunc(ctx, userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *snips.File); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFiles_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockFiles_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
func (_e *MockFiles_Expecter) FindByName(ctx any, userID any, name any) *MockFiles_FindByName_Call {
	return &MockFiles_FindByName_Call{Call: _e.mock.On("FindByName", ctx, userID, name)}
}

func (_c *MockFiles_FindByName_Call) Run(run func(ctx context.Context, userID string, name string)) *MockFiles_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFiles_FindByName_Call) Return(file *snips.File, err error) *MockFiles_FindByName_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFiles_FindByName_Call) RunAndReturn(run func(ctx context.Context, userID string, name string) (*snips.File, error)) *MockFiles_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUser provides a mock function for the type MockFiles
func (_mock *MockFiles) FindByUser(ctx context.Context, userID string, opts ...db.PageOption) ([]*snips.File, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, userID, opts)
	} else {
		tmpRet = _mock.Called(ctx, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindByUser")
	}

	var r0 []*snips.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...db.PageOption) ([]*snips.File, error)); ok {
		return returnFunc(ctx, userID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...db.PageOption) []*snips.File); ok {
		r0 = returnFunc(ctx, userID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*snips.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...db.PageOption) error); ok {
		r1 = returnFunc(ctx, userID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFiles_FindByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUser'
type MockFiles_FindByUser_Call struct {
	*mock.Call
}

// FindByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - opts ...db.PageOption
func (_e *MockFiles_Expecter) FindByUser(ctx any, userID any, opts ...any) *MockFiles_FindByUser_Call {
	return &MockFiles_FindByUser_Call{Call: _e.mock.On("FindByUser",
		append([]any{ctx, userID}, opts...)...)}
}

func (_c *MockFiles_FindByUser_Call) Run(run func(ctx context.Context, userID string, opts ...db.PageOption)) *MockFiles_FindByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []db.PageOption
		var variadicArgs []db.PageOption
		if len(args) > 2 {
			variadicArgs = args[2].([]db.PageOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFiles_FindByUser_Call) Return(files []*snips.File, err error) *MockFiles_FindByUser_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFiles_FindByUser_Call) RunAndReturn(run func(ctx context.Context, userID string, opts ...db.PageOption) ([]*snips.File, error)) *MockFiles_FindByUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindWithContent provides a mock function for the type MockFiles
func (_mock *MockFiles) FindWithContent(ctx context.Context, id string) (*snips.File, []byte, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindWithContent")
	}

	var r0 *snips.File
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*snips.File, []byte, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *snips.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) []byte); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFiles_FindWithContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWithContent'
type MockFiles_FindWithContent_Call struct {
	*mock.Call
}

// FindWithContent is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFiles_Expecter) FindWithContent(ctx any, id any) *MockFiles_FindWithContent_Call {
	return &MockFiles_FindWithContent_Call{Call: _e.mock.On("FindWithContent", ctx, id)}
}

func (_c *MockFiles_FindWithContent_Call) Run(run func(ctx context.Context, id string)) *MockFiles_FindWithContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFiles_FindWithContent_Call) Return(file *snips.File, bytes []byte, err error) *MockFiles_FindWithContent_Call {
	_c.Call.Return(file, bytes, err)
	return _c
}

func (_c *MockFiles_FindWithContent_Call) RunAndReturn(run func(ctx context.Context, id string) (*snips.File, []byte, error)) *MockFiles_FindWithContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetContent provides a mock function for the type MockFiles
func (_mock *MockFiles) GetContent(ctx context.Context, id string) ([]byte, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetContent")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFiles_GetContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContent'
type MockFiles_GetContent_Call struct {
	*mock.Call
}

// GetContent is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFiles_Expecter) GetContent(ctx any, id any) *MockFiles_GetContent_Call {
	return &MockFiles_GetContent_Call{Call: _e.mock.On("GetContent", ctx, id)}
}

func (_c *MockFiles_GetContent_Call) Run(run func(ctx context.Context, id string)) *MockFiles_GetContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFiles_GetContent_Call) Return(bytes []byte, err error) *MockFiles_GetContent_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFiles_GetContent_Call) RunAndReturn(run func(ctx context.Context, id string) ([]byte, error)) *MockFiles_GetContent_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockFiles
func (_mock *MockFiles) Update(ctx context.Context, file *snips.File) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.File) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFiles_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFiles_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - file *snips.File
func (_e *MockFiles_Expecter) Update(ctx any, file any) *MockFiles_Update_Call {
	return &MockFiles_Update_Call{Call: _e.mock.On("Update", ctx, file)}
}

func (_c *MockFiles_Update_Call) Run(run func(ctx context.Context, file *snips.File)) *MockFiles_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snips.File
		if args[1] != nil {
			arg1 = args[1].(*snips.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFiles_Update_Call) Return(err error) *MockFiles_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFiles_Update_Call) RunAndReturn(run func(ctx context.Context, file *snips.File) error) *MockFiles_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateContent provides a mock function for the type MockFiles
func (_mock *MockFiles) UpdateContent(ctx context.Context, file *snips.File, content []byte) error {
	ret := _mock.Called(ctx, file, content)

	if len(ret) == 0 {
		panic("no return value specified for UpdateContent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.File, []byte) error); ok {
		r0 = returnFunc(ctx, file, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFiles_UpdateContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateContent'
type MockFiles_UpdateContent_Call struct {
	*mock.Call
}

// UpdateContent is a helper method to define mock.On call
//   - ctx context.Context
//   - file *snips.File
//   - content []byte
func (_e *MockFiles_Expecter) UpdateContent(ctx any, file any, content any) *MockFiles_UpdateContent_Call {
	return &MockFiles_UpdateContent_Call{Call: _e.mock.On("UpdateContent", ctx, file, content)}
}

func (_c *MockFiles_UpdateContent_Call) Run(run func(ctx context.Context, file *snips.File, content []byte)) *MockFiles_UpdateContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snips.File
		if args[1] != nil {
			arg1 = args[1].(*snips.File)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFiles_UpdateContent_Call) Return(err error) *MockFiles_UpdateContent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFiles_UpdateContent_Call) RunAndReturn(run func(ctx context.Context, file *snips.File, content []byte) error) *MockFiles_UpdateContent_Call {
	_c.Call.Return(run)
	return _c
}
