// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMigrator creates a new instance of MockMigrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMigrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigrator {
	mock := &MockMigrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMigrator is an autogenerated mock type for the Migrator type
type MockMigrator struct {
	mock.Mock
}

type MockMigrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMigrator) EXPECT() *MockMigrator_Expecter {
	return &MockMigrator_Expecter{mock: &_m.Mock}
}

// Migrate provides a mock function for the type MockMigrator
func (_mock *MockMigrator) Migrate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrator_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type MockMigrator_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMigrator_Expecter) Migrate(ctx any) *MockMigrator_Migrate_Call {
	return &MockMigrator_Migrate_Call{Call: _e.mock.On("Migrate", ctx)}
}

func (_c *MockMigrator_Migrate_Call) Run(run func(ctx context.Context)) *MockMigrator_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMigrator_Migrate_Call) Return(err error) *MockMigrator_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrator_Migrate_Call) RunAndReturn(run func(ctx context.Context) error) *MockMigrator_Migrate_Call {
	_c.Call.Return(run)
	return _c
}
