// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbmock

import (
	"context"

	"github.com/robherley/snips.sh/internal/snips"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublicKeys creates a new instance of MockPublicKeys. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublicKeys(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublicKeys {
	mock := &MockPublicKeys{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublicKeys is an autogenerated mock type for the PublicKeys type
type MockPublicKeys struct {
	mock.Mock
}

type MockPublicKeys_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublicKeys) EXPECT() *MockPublicKeys_Expecter {
	return &MockPublicKeys_Expecter{mock: &_m.Mock}
}

// FindByFingerprint provides a mock function for the type MockPublicKeys
func (_mock *MockPublicKeys) FindByFingerprint(ctx context.Context, fingerprint string) (*snips.PublicKey, error) {
	ret := _mock.Called(ctx, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for FindByFingerprint")
	}

	var r0 *snips.PublicKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*snips.PublicKey, error)); ok {
		return returnFunc(ctx, fingerprint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *snips.PublicKey); ok {
		r0 = returnFunc(ctx, fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.PublicKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fingerprint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPublicKeys_FindByFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFingerprint'
type MockPublicKeys_FindByFingerprint_Call struct {
	*mock.Call
}

// FindByFingerprint is a helper method to define mock.On call
//   - ctx context.Context
//   - fingerprint string
func (_e *MockPublicKeys_Expecter) FindByFingerprint(ctx interface{}, fingerprint interface{}) *MockPublicKeys_FindByFingerprint_Call {
	return &MockPublicKeys_FindByFingerprint_Call{Call: _e.mock.On("FindByFingerprint", ctx, fingerprint)}
}

func (_c *MockPublicKeys_FindByFingerprint_Call) Run(run func(ctx context.Context, fingerprint string)) *MockPublicKeys_FindByFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublicKeys_FindByFingerprint_Call) Return(publicKey *snips.PublicKey, err error) *MockPublicKeys_FindByFingerprint_Call {
	_c.Call.Return(publicKey, err)
	return _c
}

func (_c *MockPublicKeys_FindByFingerprint_Call) RunAndReturn(run func(ctx context.Context, fingerprint string) (*snips.PublicKey, error)) *MockPublicKeys_FindByFingerprint_Call {
	_c.Call.Return(run)
	return _c
}
