// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbmock

import (
	"context"

	"github.com/robherley/snips.sh/internal/db"
	"github.com/robherley/snips.sh/internal/snips"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRevisions creates a new instance of MockRevisions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRevisions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRevisions {
	mock := &MockRevisions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRevisions is an autogenerated mock type for the Revisions type
type MockRevisions struct {
	mock.Mock
}

type MockRevisions_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRevisions) EXPECT() *MockRevisions_Expecter {
	return &MockRevisions_Expecter{mock: &_m.Mock}
}

// CountByFileID provides a mock function for the type MockRevisions
func (_mock *MockRevisions) CountByFileID(ctx context.Context, fileID string) (int64, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for CountByFileID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRevisions_CountByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByFileID'
type MockRevisions_CountByFileID_Call struct {
	*mock.Call
}

// CountByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockRevisions_Expecter) CountByFileID(ctx any, fileID any) *MockRevisions_CountByFileID_Call {
	return &MockRevisions_CountByFileID_Call{Call: _e.mock.On("CountByFileID", ctx, fileID)}
}

func (_c *MockRevisions_CountByFileID_Call) Run(run func(ctx context.Context, fileID string)) *MockRevisions_CountByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRevisions_CountByFileID_Call) Return(n int64, err error) *MockRevisions_CountByFileID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRevisions_CountByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID string) (int64, error)) *MockRevisions_CountByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRevisions
func (_mock *MockRevisions) Create(ctx context.Context, revision *snips.Revision, diff []byte, maxRevisions uint64) error {
	ret := _mock.Called(ctx, revision, diff, maxRevisions)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.Revision, []byte, uint64) error); ok {
		r0 = returnFunc(ctx, revision, diff, maxRevisions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRevisions_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRevisions_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - revision *snips.Revision
//   - diff []byte
//   - maxRevisions uint64
func (_e *MockRevisions_Expecter) Create(ctx any, revision any, diff any, maxRevisions any) *MockRevisions_Create_Call {
	return &MockRevisions_Create_Call{Call: _e.mock.On("Create", ctx, revision, diff, maxRevisions)}
}

func (_c *MockRevisions_Create_Call) Run(run func(ctx context.Context, revision *snips.Revision, diff []byte, maxRevisions uint64)) *MockRevisions_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snips.Revision
		if args[1] != nil {
			arg1 = args[1].(*snips.Revision)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRevisions_Create_Call) Return(err error) *MockRevisions_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRevisions_Create_Call) RunAndReturn(run func(ctx context.Context, revision *snips.Revision, diff []byte, maxRevisions uint64) error) *MockRevisions_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFileID provides a mock function for the type MockRevisions
func (_mock *MockRevisions) FindByFileID(ctx context.Context, fileID string, opts ...db.PageOption) ([]*snips.Revision, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, fileID, opts)
	} else {
		tmpRet = _mock.Called(ctx, fileID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindByFileID")
	}

	var r0 []*snips.Revision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...db.PageOption) ([]*snips.Revision, error)); ok {
		return returnFunc(ctx, fileID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...db.PageOption) []*snips.Revision); ok {
		r0 = returnFunc(ctx, fileID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*snips.Revision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...db.PageOption) error); ok {
		r1 = returnFunc(ctx, fileID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRevisions_FindByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFileID'
type MockRevisions_FindByFileID_Call struct {
	*mock.Call
}

// FindByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
//   - opts ...db.PageOption
func (_e *MockRevisions_Expecter) FindByFileID(ctx any, fileID any, opts ...any) *MockRevisions_FindByFileID_Call {
	return &MockRevisions_FindByFileID_Call{Call: _e.mock.On("FindByFileID",
		append([]any{ctx, fileID}, opts...)...)}
}

func (_c *MockRevisions_FindByFileID_Call) Run(run func(ctx context.Context, fileID string, opts ...db.PageOption)) *MockRevisions_FindByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []db.PageOption
		var variadicArgs []db.PageOption
		if len(args) > 2 {
			variadicArgs = args[2].([]db.PageOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRevisions_FindByFileID_Call) Return(revisions []*snips.Revision, err error) *MockRevisions_FindByFileID_Call {
	_c.Call.Return(revisions, err)
	return _c
}

func (_c *MockRevisions_FindByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID string, opts ...db.PageOption) ([]*snips.Revision, error)) *MockRevisions_FindByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFileIDAndSequence provides a mock function for the type MockRevisions
func (_mock *MockRevisions) FindByFileIDAndSequence(ctx context.Context, fileID string, sequence int64) (*snips.Revision, error) {
	ret := _mock.Called(ctx, fileID, sequence)

	if len(ret) == 0 {
		panic("no return value specified for FindByFileIDAndSequence")
	}

	var r0 *snips.Revision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (*snips.Revision, error)); ok {
		return returnFunc(ctx, fileID, sequence)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) *snips.Revision); ok {
		r0 = returnFunc(ctx, fileID, sequence)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.Revision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, fileID, sequence)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRevisions_FindByFileIDAndSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFileIDAndSequence'
type MockRevisions_FindByFileIDAndSequence_Call struct {
	*mock.Call
}

// FindByFileIDAndSequence is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
//   - sequence int64
func (_e *MockRevisions_Expecter) FindByFileIDAndSequence(ctx any, fileID any, sequence any) *MockRevisions_FindByFileIDAndSequence_Call {
	return &MockRevisions_FindByFileIDAndSequence_Call{Call: _e.mock.On("FindByFileIDAndSequence", ctx, fileID, sequence)}
}

func (_c *MockRevisions_FindByFileIDAndSequence_Call) Run(run func(ctx context.Context, fileID string, sequence int64)) *MockRevisions_FindByFileIDAndSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRevisions_FindByFileIDAndSequence_Call) Return(revision *snips.Revision, err error) *MockRevisions_FindByFileIDAndSequence_Call {
	_c.Call.Return(revision, err)
	return _c
}

func (_c *MockRevisions_FindByFileIDAndSequence_Call) RunAndReturn(run func(ctx context.Context, fileID string, sequence int64) (*snips.Revision, error)) *MockRevisions_FindByFileIDAndSequence_Call {
	_c.Call.Return(run)
	return _c
}

// FindDiff provides a mock function for the type MockRevisions
func (_mock *MockRevisions) FindDiff(ctx context.Context, id string) ([]byte, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindDiff")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRevisions_FindDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDiff'
type MockRevisions_FindDiff_Call struct {
	*mock.Call
}

// FindDiff is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRevisions_Expecter) FindDiff(ctx any, id any) *MockRevisions_FindDiff_Call {
	return &MockRevisions_FindDiff_Call{Call: _e.mock.On("FindDiff", ctx, id)}
}

func (_c *MockRevisions_FindDiff_Call) Run(run func(ctx context.Context, id string)) *MockRevisions_FindDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRevisions_FindDiff_Call) Return(bytes []byte, err error) *MockRevisions_FindDiff_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRevisions_FindDiff_Call) RunAndReturn(run func(ctx context.Context, id string) ([]byte, error)) *MockRevisions_FindDiff_Call {
	_c.Call.Return(run)
	return _c
}
