// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbmock

import (
	"context"

	"github.com/robherley/snips.sh/internal/snips"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsers creates a new instance of MockUsers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsers {
	mock := &MockUsers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsers is an autogenerated mock type for the Users type
type MockUsers struct {
	mock.Mock
}

type MockUsers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsers) EXPECT() *MockUsers_Expecter {
	return &MockUsers_Expecter{mock: &_m.Mock}
}

// CreateWithPublicKey provides a mock function for the type MockUsers
func (_mock *MockUsers) CreateWithPublicKey(ctx context.Context, publickey *snips.PublicKey) (*snips.User, error) {
	ret := _mock.Called(ctx, publickey)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithPublicKey")
	}

	var r0 *snips.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.PublicKey) (*snips.User, error)); ok {
		return returnFunc(ctx, publickey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.PublicKey) *snips.User); ok {
		r0 = returnFunc(ctx, publickey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *snips.PublicKey) error); ok {
		r1 = returnFunc(ctx, publickey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsers_CreateWithPublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithPublicKey'
type MockUsers_CreateWithPublicKey_Call struct {
	*mock.Call
}

// CreateWithPublicKey is a helper method to define mock.On call
//   - ctx context.Context
//   - publickey *snips.PublicKey
func (_e *MockUsers_Expecter) CreateWithPublicKey(ctx interface{}, publickey interface{}) *MockUsers_CreateWithPublicKey_Call {
	return &MockUsers_CreateWithPublicKey_Call{Call: _e.mock.On("CreateWithPublicKey", ctx, publickey)}
}

func (_c *MockUsers_CreateWithPublicKey_Call) Run(run func(ctx context.Context, publickey *snips.PublicKey)) *MockUsers_CreateWithPublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snips.PublicKey
		if args[1] != nil {
			arg1 = args[1].(*snips.PublicKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsers_CreateWithPublicKey_Call) Return(user *snips.User, err error) *MockUsers_CreateWithPublicKey_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsers_CreateWithPublicKey_Call) RunAndReturn(run func(ctx context.Context, publickey *snips.PublicKey) (*snips.User, error)) *MockUsers_CreateWithPublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockUsers
func (_mock *MockUsers) Find(ctx context.Context, id string) (*snips.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *snips.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*snips.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *snips.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsers_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockUsers_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUsers_Expecter) Find(ctx interface{}, id interface{}) *MockUsers_Find_Call {
	return &MockUsers_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockUsers_Find_Call) Run(run func(ctx context.Context, id string)) *MockUsers_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsers_Find_Call) Return(user *snips.User, err error) *MockUsers_Find_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsers_Find_Call) RunAndReturn(run func(ctx context.Context, id string) (*snips.User, error)) *MockUsers_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUsers
func (_mock *MockUsers) Update(ctx context.Context, user *snips.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsers_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUsers_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *snips.User
func (_e *MockUsers_Expecter) Update(ctx interface{}, user interface{}) *MockUsers_Update_Call {
	return &MockUsers_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUsers_Update_Call) Run(run func(ctx context.Context, user *snips.User)) *MockUsers_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snips.User
		if args[1] != nil {
			arg1 = args[1].(*snips.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsers_Update_Call) Return(err error) *MockUsers_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsers_Update_Call) RunAndReturn(run func(ctx context.Context, user *snips.User) error) *MockUsers_Update_Call {
	_c.Call.Return(run)
	return _c
}
