#!/bin/bash

# This script downloads and installs libtensorflow (CPU only) for the current platform.
# If you are on macOS, you can just use `brew install libtensorflow` instead.
# https://www.tensorflow.org/install/lang_c

set -e

if [ "$(uname -m)" != "x86_64" ]; then
  echo "unsupported architecture: $(uname -m)"
  exit 1
fi

OS=$(uname -s | tr '[:upper:]' '[:lower:]')

function maybe_sudo() {
  if [ "$(id -u)" -ne 0 ]; then
    sudo "$@"
  else
    "$@"
  fi
}

case "$OS" in
  darwin)
    brew install libtensorflow
    ;;
  linux)
    TENSORFLOW_VERSION=2.11.0
    ARCHIVE_PATH=$(mktemp -d)/tensorflow.tar.gz
    curl -o "$ARCHIVE_PATH" "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-${OS}-x86_64-${TENSORFLOW_VERSION}.tar.gz"
    maybe_sudo tar -xzf "$ARCHIVE_PATH" -C /usr/local
    maybe_sudo ldconfig /usr/local/lib
    rm -rf "$ARCHIVE_PATH"
    ;;
  *)
    echo "unsupported OS: $OS"
    exit 1
    ;;
esac
