#!/bin/sh

REPO_ROOT="$(git rev-parse --show-toplevel)"
source "${REPO_ROOT}/script/env"

BINDIR="${REPO_ROOT}/bin"

GOLANGCI_LINT_BINARY=$BINDIR/golangci-lint
GOLANGCI_LINT_VERSION=v2.9.0

if [ ! -f "$GOLANGCI_LINT_BINARY" ]; then
  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s "$GOLANGCI_LINT_VERSION"
fi

$GOLANGCI_LINT_BINARY run
