#!/bin/sh

set -eu

MOCKERY_VERSION="v3.6.3"

if ! command -v mockery > /dev/null 2>&1; then
    echo "mockery not found, installing ${MOCKERY_VERSION}..."
    go install "github.com/vektra/mockery/v3@${MOCKERY_VERSION}"
fi

mockery "$@"
