#!/bin/bash

TAPEDIR="$(git rev-parse --show-toplevel)"/docs/tapes

if ! command -v vhs &> /dev/null
then
  echo "vhs not be found, please install it:"
  echo "https://github.com/charmbracelet/vhs#installation"
  exit 1
fi

# if there's parametes passed to the script, use those as the tape names
if [ $# -gt 0 ]; then
  for tape in "$@"; do
    vhs "$TAPEDIR/$tape".tape -o "$TAPEDIR"/"$tape".gif
  done
  exit
else
  echo "specify a tape name to record"
  exit 1
fi
