#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
source "${REPO_ROOT}/script/env"

go run -tags onnxruntime -ldflags "-extldflags '${GO_EXTLDFLAGS}'" "${REPO_ROOT}" "$@"
