#!/usr/bin/env bash

log() {
  if [ -t 1 ]; then
    echo -e "\033[1;33m$1\033[0m"
  else
    echo "$1"
  fi
}

db=${1:-tmp/default.db}

if [ ! -f "$db" ]; then
  echo "file '$db' does not exist"
  exit 1
fi

tables=$(sqlite3 "$db" ".tables")

for table in $tables; do
  log "-- $table schema"
  sqlite3 "$db" ".schema $table"
done
