#!/bin/sh

REPO_ROOT="$(git rev-parse --show-toplevel)"
BINDIR="${REPO_ROOT}/bin"
BINARY=$BINDIR/gotestsum
GOTESTSUM_VERSION=v1.10.0

if [ ! -f "$BINARY" ]; then
  GOBIN=$BINDIR go install gotest.tools/gotestsum@${GOTESTSUM_VERSION}
fi

source "${REPO_ROOT}/script/env"
$BINARY --raw-command -- go test -json -ldflags "-extldflags \"${GO_EXTLDFLAGS}\"" ./...
