// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db

import (
	"context"

	"github.com/robherley/snips.sh/internal/snips"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// CountRevisionsByFileID provides a mock function for the type MockDB
func (_mock *MockDB) CountRevisionsByFileID(ctx context.Context, fileID string) (int64, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for CountRevisionsByFileID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_CountRevisionsByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRevisionsByFileID'
type MockDB_CountRevisionsByFileID_Call struct {
	*mock.Call
}

// CountRevisionsByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockDB_Expecter) CountRevisionsByFileID(ctx interface{}, fileID interface{}) *MockDB_CountRevisionsByFileID_Call {
	return &MockDB_CountRevisionsByFileID_Call{Call: _e.mock.On("CountRevisionsByFileID", ctx, fileID)}
}

func (_c *MockDB_CountRevisionsByFileID_Call) Run(run func(ctx context.Context, fileID string)) *MockDB_CountRevisionsByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_CountRevisionsByFileID_Call) Return(n int64, err error) *MockDB_CountRevisionsByFileID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDB_CountRevisionsByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID string) (int64, error)) *MockDB_CountRevisionsByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFile provides a mock function for the type MockDB
func (_mock *MockDB) CreateFile(ctx context.Context, file *snips.File, maxFiles uint64) error {
	ret := _mock.Called(ctx, file, maxFiles)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.File, uint64) error); ok {
		r0 = returnFunc(ctx, file, maxFiles)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_CreateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFile'
type MockDB_CreateFile_Call struct {
	*mock.Call
}

// CreateFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file *snips.File
//   - maxFiles uint64
func (_e *MockDB_Expecter) CreateFile(ctx interface{}, file interface{}, maxFiles interface{}) *MockDB_CreateFile_Call {
	return &MockDB_CreateFile_Call{Call: _e.mock.On("CreateFile", ctx, file, maxFiles)}
}

func (_c *MockDB_CreateFile_Call) Run(run func(ctx context.Context, file *snips.File, maxFiles uint64)) *MockDB_CreateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snips.File
		if args[1] != nil {
			arg1 = args[1].(*snips.File)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDB_CreateFile_Call) Return(err error) *MockDB_CreateFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_CreateFile_Call) RunAndReturn(run func(ctx context.Context, file *snips.File, maxFiles uint64) error) *MockDB_CreateFile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRevision provides a mock function for the type MockDB
func (_mock *MockDB) CreateRevision(ctx context.Context, revision *snips.Revision, maxRevisions uint64) error {
	ret := _mock.Called(ctx, revision, maxRevisions)

	if len(ret) == 0 {
		panic("no return value specified for CreateRevision")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.Revision, uint64) error); ok {
		r0 = returnFunc(ctx, revision, maxRevisions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_CreateRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRevision'
type MockDB_CreateRevision_Call struct {
	*mock.Call
}

// CreateRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - revision *snips.Revision
//   - maxRevisions uint64
func (_e *MockDB_Expecter) CreateRevision(ctx interface{}, revision interface{}, maxRevisions interface{}) *MockDB_CreateRevision_Call {
	return &MockDB_CreateRevision_Call{Call: _e.mock.On("CreateRevision", ctx, revision, maxRevisions)}
}

func (_c *MockDB_CreateRevision_Call) Run(run func(ctx context.Context, revision *snips.Revision, maxRevisions uint64)) *MockDB_CreateRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snips.Revision
		if args[1] != nil {
			arg1 = args[1].(*snips.Revision)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDB_CreateRevision_Call) Return(err error) *MockDB_CreateRevision_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_CreateRevision_Call) RunAndReturn(run func(ctx context.Context, revision *snips.Revision, maxRevisions uint64) error) *MockDB_CreateRevision_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserWithPublicKey provides a mock function for the type MockDB
func (_mock *MockDB) CreateUserWithPublicKey(ctx context.Context, publickey *snips.PublicKey) (*snips.User, error) {
	ret := _mock.Called(ctx, publickey)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserWithPublicKey")
	}

	var r0 *snips.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.PublicKey) (*snips.User, error)); ok {
		return returnFunc(ctx, publickey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.PublicKey) *snips.User); ok {
		r0 = returnFunc(ctx, publickey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *snips.PublicKey) error); ok {
		r1 = returnFunc(ctx, publickey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_CreateUserWithPublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserWithPublicKey'
type MockDB_CreateUserWithPublicKey_Call struct {
	*mock.Call
}

// CreateUserWithPublicKey is a helper method to define mock.On call
//   - ctx context.Context
//   - publickey *snips.PublicKey
func (_e *MockDB_Expecter) CreateUserWithPublicKey(ctx interface{}, publickey interface{}) *MockDB_CreateUserWithPublicKey_Call {
	return &MockDB_CreateUserWithPublicKey_Call{Call: _e.mock.On("CreateUserWithPublicKey", ctx, publickey)}
}

func (_c *MockDB_CreateUserWithPublicKey_Call) Run(run func(ctx context.Context, publickey *snips.PublicKey)) *MockDB_CreateUserWithPublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snips.PublicKey
		if args[1] != nil {
			arg1 = args[1].(*snips.PublicKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_CreateUserWithPublicKey_Call) Return(user *snips.User, err error) *MockDB_CreateUserWithPublicKey_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockDB_CreateUserWithPublicKey_Call) RunAndReturn(run func(ctx context.Context, publickey *snips.PublicKey) (*snips.User, error)) *MockDB_CreateUserWithPublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type MockDB
func (_mock *MockDB) DeleteFile(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockDB_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDB_Expecter) DeleteFile(ctx interface{}, id interface{}) *MockDB_DeleteFile_Call {
	return &MockDB_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, id)}
}

func (_c *MockDB_DeleteFile_Call) Run(run func(ctx context.Context, id string)) *MockDB_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_DeleteFile_Call) Return(err error) *MockDB_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockDB_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// FindFile provides a mock function for the type MockDB
func (_mock *MockDB) FindFile(ctx context.Context, id string) (*snips.File, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindFile")
	}

	var r0 *snips.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*snips.File, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *snips.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_FindFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFile'
type MockDB_FindFile_Call struct {
	*mock.Call
}

// FindFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDB_Expecter) FindFile(ctx interface{}, id interface{}) *MockDB_FindFile_Call {
	return &MockDB_FindFile_Call{Call: _e.mock.On("FindFile", ctx, id)}
}

func (_c *MockDB_FindFile_Call) Run(run func(ctx context.Context, id string)) *MockDB_FindFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_FindFile_Call) Return(file *snips.File, err error) *MockDB_FindFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockDB_FindFile_Call) RunAndReturn(run func(ctx context.Context, id string) (*snips.File, error)) *MockDB_FindFile_Call {
	_c.Call.Return(run)
	return _c
}

// FindFilesByUser provides a mock function for the type MockDB
func (_mock *MockDB) FindFilesByUser(ctx context.Context, userID string) ([]*snips.File, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindFilesByUser")
	}

	var r0 []*snips.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*snips.File, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*snips.File); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*snips.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_FindFilesByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFilesByUser'
type MockDB_FindFilesByUser_Call struct {
	*mock.Call
}

// FindFilesByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockDB_Expecter) FindFilesByUser(ctx interface{}, userID interface{}) *MockDB_FindFilesByUser_Call {
	return &MockDB_FindFilesByUser_Call{Call: _e.mock.On("FindFilesByUser", ctx, userID)}
}

func (_c *MockDB_FindFilesByUser_Call) Run(run func(ctx context.Context, userID string)) *MockDB_FindFilesByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_FindFilesByUser_Call) Return(files []*snips.File, err error) *MockDB_FindFilesByUser_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockDB_FindFilesByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*snips.File, error)) *MockDB_FindFilesByUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindPublicKeyByFingerprint provides a mock function for the type MockDB
func (_mock *MockDB) FindPublicKeyByFingerprint(ctx context.Context, fingerprint string) (*snips.PublicKey, error) {
	ret := _mock.Called(ctx, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for FindPublicKeyByFingerprint")
	}

	var r0 *snips.PublicKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*snips.PublicKey, error)); ok {
		return returnFunc(ctx, fingerprint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *snips.PublicKey); ok {
		r0 = returnFunc(ctx, fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.PublicKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fingerprint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_FindPublicKeyByFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPublicKeyByFingerprint'
type MockDB_FindPublicKeyByFingerprint_Call struct {
	*mock.Call
}

// FindPublicKeyByFingerprint is a helper method to define mock.On call
//   - ctx context.Context
//   - fingerprint string
func (_e *MockDB_Expecter) FindPublicKeyByFingerprint(ctx interface{}, fingerprint interface{}) *MockDB_FindPublicKeyByFingerprint_Call {
	return &MockDB_FindPublicKeyByFingerprint_Call{Call: _e.mock.On("FindPublicKeyByFingerprint", ctx, fingerprint)}
}

func (_c *MockDB_FindPublicKeyByFingerprint_Call) Run(run func(ctx context.Context, fingerprint string)) *MockDB_FindPublicKeyByFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_FindPublicKeyByFingerprint_Call) Return(publicKey *snips.PublicKey, err error) *MockDB_FindPublicKeyByFingerprint_Call {
	_c.Call.Return(publicKey, err)
	return _c
}

func (_c *MockDB_FindPublicKeyByFingerprint_Call) RunAndReturn(run func(ctx context.Context, fingerprint string) (*snips.PublicKey, error)) *MockDB_FindPublicKeyByFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// FindRevisionByFileIDAndSequence provides a mock function for the type MockDB
func (_mock *MockDB) FindRevisionByFileIDAndSequence(ctx context.Context, fileID string, sequence int64) (*snips.Revision, error) {
	ret := _mock.Called(ctx, fileID, sequence)

	if len(ret) == 0 {
		panic("no return value specified for FindRevisionByFileIDAndSequence")
	}

	var r0 *snips.Revision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (*snips.Revision, error)); ok {
		return returnFunc(ctx, fileID, sequence)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) *snips.Revision); ok {
		r0 = returnFunc(ctx, fileID, sequence)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.Revision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, fileID, sequence)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_FindRevisionByFileIDAndSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRevisionByFileIDAndSequence'
type MockDB_FindRevisionByFileIDAndSequence_Call struct {
	*mock.Call
}

// FindRevisionByFileIDAndSequence is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
//   - sequence int64
func (_e *MockDB_Expecter) FindRevisionByFileIDAndSequence(ctx interface{}, fileID interface{}, sequence interface{}) *MockDB_FindRevisionByFileIDAndSequence_Call {
	return &MockDB_FindRevisionByFileIDAndSequence_Call{Call: _e.mock.On("FindRevisionByFileIDAndSequence", ctx, fileID, sequence)}
}

func (_c *MockDB_FindRevisionByFileIDAndSequence_Call) Run(run func(ctx context.Context, fileID string, sequence int64)) *MockDB_FindRevisionByFileIDAndSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDB_FindRevisionByFileIDAndSequence_Call) Return(revision *snips.Revision, err error) *MockDB_FindRevisionByFileIDAndSequence_Call {
	_c.Call.Return(revision, err)
	return _c
}

func (_c *MockDB_FindRevisionByFileIDAndSequence_Call) RunAndReturn(run func(ctx context.Context, fileID string, sequence int64) (*snips.Revision, error)) *MockDB_FindRevisionByFileIDAndSequence_Call {
	_c.Call.Return(run)
	return _c
}

// FindRevisionsByFileID provides a mock function for the type MockDB
func (_mock *MockDB) FindRevisionsByFileID(ctx context.Context, fileID string) ([]*snips.Revision, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for FindRevisionsByFileID")
	}

	var r0 []*snips.Revision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*snips.Revision, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*snips.Revision); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*snips.Revision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_FindRevisionsByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRevisionsByFileID'
type MockDB_FindRevisionsByFileID_Call struct {
	*mock.Call
}

// FindRevisionsByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockDB_Expecter) FindRevisionsByFileID(ctx interface{}, fileID interface{}) *MockDB_FindRevisionsByFileID_Call {
	return &MockDB_FindRevisionsByFileID_Call{Call: _e.mock.On("FindRevisionsByFileID", ctx, fileID)}
}

func (_c *MockDB_FindRevisionsByFileID_Call) Run(run func(ctx context.Context, fileID string)) *MockDB_FindRevisionsByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_FindRevisionsByFileID_Call) Return(revisions []*snips.Revision, err error) *MockDB_FindRevisionsByFileID_Call {
	_c.Call.Return(revisions, err)
	return _c
}

func (_c *MockDB_FindRevisionsByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID string) ([]*snips.Revision, error)) *MockDB_FindRevisionsByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUser provides a mock function for the type MockDB
func (_mock *MockDB) FindUser(ctx context.Context, id string) (*snips.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUser")
	}

	var r0 *snips.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*snips.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *snips.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snips.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_FindUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUser'
type MockDB_FindUser_Call struct {
	*mock.Call
}

// FindUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDB_Expecter) FindUser(ctx interface{}, id interface{}) *MockDB_FindUser_Call {
	return &MockDB_FindUser_Call{Call: _e.mock.On("FindUser", ctx, id)}
}

func (_c *MockDB_FindUser_Call) Run(run func(ctx context.Context, id string)) *MockDB_FindUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_FindUser_Call) Return(user *snips.User, err error) *MockDB_FindUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockDB_FindUser_Call) RunAndReturn(run func(ctx context.Context, id string) (*snips.User, error)) *MockDB_FindUser_Call {
	_c.Call.Return(run)
	return _c
}

// Migrate provides a mock function for the type MockDB
func (_mock *MockDB) Migrate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type MockDB_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDB_Expecter) Migrate(ctx interface{}) *MockDB_Migrate_Call {
	return &MockDB_Migrate_Call{Call: _e.mock.On("Migrate", ctx)}
}

func (_c *MockDB_Migrate_Call) Run(run func(ctx context.Context)) *MockDB_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDB_Migrate_Call) Return(err error) *MockDB_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_Migrate_Call) RunAndReturn(run func(ctx context.Context) error) *MockDB_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFile provides a mock function for the type MockDB
func (_mock *MockDB) UpdateFile(ctx context.Context, file *snips.File) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *snips.File) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_UpdateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFile'
type MockDB_UpdateFile_Call struct {
	*mock.Call
}

// UpdateFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file *snips.File
func (_e *MockDB_Expecter) UpdateFile(ctx interface{}, file interface{}) *MockDB_UpdateFile_Call {
	return &MockDB_UpdateFile_Call{Call: _e.mock.On("UpdateFile", ctx, file)}
}

func (_c *MockDB_UpdateFile_Call) Run(run func(ctx context.Context, file *snips.File)) *MockDB_UpdateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snips.File
		if args[1] != nil {
			arg1 = args[1].(*snips.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_UpdateFile_Call) Return(err error) *MockDB_UpdateFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_UpdateFile_Call) RunAndReturn(run func(ctx context.Context, file *snips.File) error) *MockDB_UpdateFile_Call {
	_c.Call.Return(run)
	return _c
}
